module.exports ={
    LOADMARKET : 'LOADMARKET',
    SETLATMARKET : 'SETLATMARKET',
    SETLNGMARKET : 'SETLNGMARKET',
    SETZOOM: 'SETZOOM',
    SETPLACE: 'SETPLACE',
    SETPLACEID: 'SETPLACEID',

}